#pragma once

#define BASE_COLOR_TEXTURE_UNIT   0
#define BASE_NORMAL_TEXTURE_UNIT  1
#define BASE_NIGHT_TEXTURE_UNIT   2
#define BASE_DETAILS_TEXTURE_UNIT 3
#define BASE_ENV_TEXTURE_UNIT     4
#define BASE_DECAL_TEXTURE_UNIT   5
#define BASE_LM_TEXTURE_UNIT      6
#define BASE_REFL_TEXTURE_UNIT    7
#define BASE_SHADOW_TEXTURE_UNIT  8

#define BASE_HW_ANIMATION_TEXTURE_UNIT  11
#define BASE_HW_INST_TEXTURE_UNIT  12

#define BASE_LIGHTS_TEXTURE_UNIT   13

#define GLSL_VERSION             130